import type { Metadata } from "next";
import "./styles/globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import { dubaiFont, readexProFont } from "./fonts";

export const metadata: Metadata = {
  title: "FAR4 Solutions Group",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" suppressHydrationWarning>
      <body
        dir="rtl"
        className={`${dubaiFont.variable} ${readexProFont.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
